// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuyhloyibzxaejgssofa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1eWhsb3lpYnp4YWVqZ3Nzb2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODcyODAsImV4cCI6MjA2NDU2MzI4MH0.-S3olaMJaukKr1cYPKN7cOjCQ29bIjOpawZJnmPOU3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);